# Data Ingestion System Configuration

# Cache configuration
cache:
  redis_url: "${REDIS_URL:redis://localhost:6379}"
  default_ttl: 300  # 5 minutes
  max_memory: "1gb"
  compression: true
  eviction_policy: "lru"

# Monitoring configuration  
monitoring:
  metrics_port: 9090
  log_level: "${LOG_LEVEL:INFO}"
  structured_logging: true
  correlation_ids: true
  alert_thresholds:
    error_rate: 0.05
    latency_p95: 2000  # milliseconds
    cache_hit_rate_min: 0.8
    data_quality_min: 0.7

# Validation configuration
validation:
  quality_threshold: 0.7
  completeness_threshold: 0.9
  max_staleness_seconds: 300
  price_bounds:
    min_price: 0.0
    max_price: 1000000.0
  volume_bounds:
    min_volume: 0.0

# Circuit breaker configuration
circuit_breaker:
  failure_threshold: 5
  timeout_seconds: 60
  half_open_max_calls: 3

# Rate limiting configuration
rate_limiting:
  default_requests_per_minute: 60
  burst_allowance: 10
  backoff_multiplier: 2.0
  max_backoff_seconds: 300